name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando Login"

    - name: Build Docker Image
      run: |
        echo "Ejecutando el Build"
        docker build -t hugondd/docker-graphql:0.0.2 .
        echo "Fin Ejecutando el Build"

    - name: Push Docker Image
      run: |
        echo "Inicia Ejecucion Push"
        docker push hugondd/docker-graphql:0.0.2 .
        echo "Fin Ejecucion Push"
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
